### ISSUE TITLE
Is this the official repo for this project?

### ISSUE THREAD

**Issue by gingerbeardman** [natowi/prs-plus#388]
Please let me know either way.

**Comment by gingerbeardman** [comment]
@kurtu sent me here, so I will fork and add my own details to this wonderful (old) project. Who knows, maybe somebody else out there is still using PRS+ on a Sony PRS-650 or similar?

**Comment by kartu** [comment]
Erm, sorry, this one is the right one:
https://github.com/kartu/prs-plus

I've added you as collaborator.

regards,
kartu
